{
  "uid" : "173887aeddeb6c94",
  "name" : "test_value_error[-2147483649-1-division]",
  "fullName" : "tests.test_functionality#test_value_error",
  "historyId" : "cadcd17e8e19030525d83fd89e425133",
  "time" : {
    "start" : 1649601496670,
    "stop" : 1649601496673,
    "duration" : 3
  },
  "status" : "passed",
  "statusMessage" : "XPASS Ответ от сервера не соответствует ТЗ",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "setup_app",
    "time" : {
      "start" : 1649601435536,
      "stop" : 1649601440410,
      "duration" : 4874
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "setup_app::0",
    "time" : {
      "start" : 1649601497229,
      "stop" : 1649601499117,
      "duration" : 1888
    },
    "status" : "broken",
    "statusMessage" : "UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 685: character maps to <undefined>\n",
    "statusTrace" : "  File \"C:\\Users\\Oleg\\Desktop\\Study\\Test tasks\\Test_task_infotecs\\CalcAutoTest\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Oleg\\Desktop\\Study\\Test tasks\\Test_task_infotecs\\CalcAutoTest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Oleg\\Desktop\\Study\\Test tasks\\Test_task_infotecs\\CalcAutoTest\\tests\\conftest.py\", line 23, in setup_app\n    gif = f.read()\n  File \"C:\\Users\\Oleg\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\encodings\\cp1251.py\", line 23, in decode\n    return codecs.charmap_decode(input,self.errors,decoding_table)[0]\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : true,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "ERROR=4 check"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_functionality"
  }, {
    "name" : "host",
    "value" : "LAPTOP-60Q9K2PF"
  }, {
    "name" : "thread",
    "value" : "12828-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_functionality"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "task",
    "value" : "'division'"
  }, {
    "name" : "x",
    "value" : "-2147483649"
  }, {
    "name" : "y",
    "value" : "1"
  } ],
  "links" : [ {
    "name" : "Bug",
    "url" : "Bug",
    "type" : "issue"
  } ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')" ]
  },
  "source" : "173887aeddeb6c94.json",
  "parameterValues" : [ "'division'", "-2147483649", "1" ]
}