{
  "uid" : "687a0440e3973fcd",
  "name" : "test_value_error[2147483648-1-remainder]",
  "fullName" : "tests.test_functionality#test_value_error",
  "historyId" : "59a9f0a66949bf4ed4e363e2f61f6f3d",
  "time" : {
    "start" : 1649600775490,
    "stop" : 1649600775494,
    "duration" : 4
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 0, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 0}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 0, 'statusCode': 0}",
  "statusTrace" : "x = 2147483648, y = 1, task = 'remainder'\n\n    @allure.issue(\"Bug\")\n    @allure.feature(\"ERROR=4 check\")\n    @pytest.mark.xfail(reason=\"Ответ от сервера не соответствует ТЗ\")\n    @pytest.mark.parametrize(\"task\", [\"addition\", \"multiplication\", \"division\", \"remainder\"])\n    @pytest.mark.parametrize(\"x, y\", [(-2147483649, 1), (2147483648, 1), (1, -2147483649), (1, 2147483648)])\n    def test_value_error(x, y, task):\n        respond = requests.post(f\"http://{HOST}:{PORT}/api/{task}\", json={\"x\": x, \"y\": y})\n>       assert respond.json() == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE       AssertionError: assert {'result': 0, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE         Differing items:\nE         {'statusCode': 0} != {'statusCode': 4}\nE         Left contains 1 more item:\nE         {'result': 0}\nE         Right contains 1 more item:\nE         {'statusMessage': 'Превышены максимальные значения параметров'}\nE         Full diff:\nE         - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE         + {'result': 0, 'statusCode': 0}\n\ntest_functionality.py:24: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "setup_app",
    "time" : {
      "start" : 1649600715356,
      "stop" : 1649600720222,
      "duration" : 4866
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "setup_app::0",
    "time" : {
      "start" : 1649600775896,
      "stop" : 1649600777616,
      "duration" : 1720
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "5964041eda4f3a20",
      "name" : "!!!FINISH IT!!!",
      "source" : "5964041eda4f3a20.gif",
      "type" : "image/gif",
      "size" : 28
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1,
    "stepsCount" : 0,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "ERROR=4 check"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_functionality"
  }, {
    "name" : "host",
    "value" : "LAPTOP-60Q9K2PF"
  }, {
    "name" : "thread",
    "value" : "11156-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_functionality"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "task",
    "value" : "'remainder'"
  }, {
    "name" : "x",
    "value" : "2147483648"
  }, {
    "name" : "y",
    "value" : "1"
  } ],
  "links" : [ {
    "name" : "Bug",
    "url" : "Bug",
    "type" : "issue"
  } ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')" ]
  },
  "source" : "687a0440e3973fcd.json",
  "parameterValues" : [ "'remainder'", "2147483648", "1" ]
}