{
  "uid" : "fa2948d9ae5fbab3",
  "name" : "test_value_error[2147483648-1-addition]",
  "fullName" : "tests.test_functionality#test_value_error",
  "historyId" : "4ab2298c331d1f3a2e9945e821d2e55d",
  "time" : {
    "start" : 1649601892215,
    "stop" : 1649601892219,
    "duration" : 4
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 2147483649}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 2147483649, 'statusCode': 0}",
  "statusTrace" : "x = 2147483648, y = 1, task = 'addition'\n\n    @allure.issue(\"Bug\")\n    @allure.feature(\"ERROR=4 check\")\n    @pytest.mark.xfail(reason=\"Ответ от сервера не соответствует ТЗ\")\n    @pytest.mark.parametrize(\"task\", [\"addition\", \"multiplication\", \"division\", \"remainder\"])\n    @pytest.mark.parametrize(\"x, y\", [(-2147483649, 1), (2147483648, 1), (1, -2147483649), (1, 2147483648)])\n    def test_value_error(x, y, task):\n        respond = requests.post(f\"http://{HOST}:{PORT}/api/{task}\", json={\"x\": x, \"y\": y})\n>       assert respond.json() == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE       AssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE         Differing items:\nE         {'statusCode': 0} != {'statusCode': 4}\nE         Left contains 1 more item:\nE         {'result': 2147483649}\nE         Right contains 1 more item:\nE         {'statusMessage': 'Превышены максимальные значения параметров'}\nE         Full diff:\nE         - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\nE         + {'result': 2147483649, 'statusCode': 0}\n\ntest_functionality.py:24: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 4,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "setup_app",
    "time" : {
      "start" : 1649601832363,
      "stop" : 1649601837215,
      "duration" : 4852
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "setup_app::0",
    "time" : {
      "start" : 1649601892756,
      "stop" : 1649601894516,
      "duration" : 1760
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "438b6eba3afea2fd",
      "name" : "!!!FINISH IT!!!",
      "source" : "438b6eba3afea2fd.gif",
      "type" : "image/gif",
      "size" : 7151672
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1,
    "stepsCount" : 0,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "feature",
    "value" : "ERROR=4 check"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_functionality"
  }, {
    "name" : "host",
    "value" : "LAPTOP-60Q9K2PF"
  }, {
    "name" : "thread",
    "value" : "26948-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_functionality"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "task",
    "value" : "'addition'"
  }, {
    "name" : "x",
    "value" : "2147483648"
  }, {
    "name" : "y",
    "value" : "1"
  } ],
  "links" : [ {
    "name" : "Bug",
    "url" : "Bug",
    "type" : "issue"
  } ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "294f3b462e780440",
      "status" : "skipped",
      "statusDetails" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 2147483649}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 2147483649, 'statusCode': 0}",
      "time" : {
        "start" : 1649601496687,
        "stop" : 1649601496691,
        "duration" : 4
      }
    }, {
      "uid" : "4538d3ea53f84f5f",
      "status" : "skipped",
      "statusDetails" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 2147483649}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 2147483649, 'statusCode': 0}",
      "time" : {
        "start" : 1649600775333,
        "stop" : 1649600775336,
        "duration" : 3
      }
    }, {
      "uid" : "f28f5c242becf9d0",
      "status" : "skipped",
      "statusDetails" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 2147483649}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 2147483649, 'statusCode': 0}",
      "time" : {
        "start" : 1649598827389,
        "stop" : 1649598827393,
        "duration" : 4
      }
    }, {
      "uid" : "3c211e8bd2b6186d",
      "status" : "skipped",
      "statusDetails" : "XFAIL Ответ от сервера не соответствует ТЗ\n\nAssertionError: assert {'result': 2147483649, 'statusCode': 0} == {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  Differing items:\n  {'statusCode': 0} != {'statusCode': 4}\n  Left contains 1 more item:\n  {'result': 2147483649}\n  Right contains 1 more item:\n  {'statusMessage': 'Превышены максимальные значения параметров'}\n  Full diff:\n  - {'statusCode': 4, 'statusMessage': 'Превышены максимальные значения параметров'}\n  + {'result': 2147483649, 'statusCode': 0}",
      "time" : {
        "start" : 1649597959218,
        "stop" : 1649597959222,
        "duration" : 4
      }
    } ],
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='Ответ от сервера не соответствует ТЗ')" ]
  },
  "source" : "fa2948d9ae5fbab3.json",
  "parameterValues" : [ "'addition'", "2147483648", "1" ]
}